name: Formatter Check

on:
  pull_request:
    branches: [main]

jobs:
  frontend-formatter:
    name: Dart Formatter Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.5"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check Dart format
        run: dart format --output=none --set-exit-if-changed .

      - name: Flutter analyze
        run: flutter analyze

  backend-formatter:
    name: Go Formatter Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Check Go format
        run: |
          set -e
          FILES=$(gofmt -l -s .)
          if [ -n "$FILES" ]; then
            echo "These files are not gofmt-ed:"
            echo "$FILES"
            exit 1
          fi

  backend-test:
    name: Go Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test ./... -v -coverprofile=coverage.out || true
          go tool cover -func=coverage.out || true
